# Task:
#   Each new number in the Fibonacci sequence is generated by adding the previous two
#   numbers. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... Write
#   a program to display the 20 first numbers of the Fibonacci sequence.

# ------------------------------------------------------------------------------------------------
# Possible solution:
first = 1
second = 1
counter = 1
while counter <= 20:
    print(second)
    temp = first + second
    first = second
    second = temp
    counter += 1

# Improvement: temporary variable can be avoided
first = 1
second = 1
counter = 1
while counter <= 20:
    print(second)
    second = first + second
    first = second - first
    counter += 1
    
# If for-loops are allowed:
first = 1
second = 1
for _ in range(20):
    print(second)
    second = first + second
    first = second - first
    
# ------------------------------------------------------------------------------------------------
# Advanced solution:
#   Using tuple assignment ("multiple assignment"):
first, second = 1, 1
for _ in range(20):
    first, second = second, first + second
    print(first)
